// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: pulsestream.proto

package clutta_sync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PulseStreamService_SendPulse_FullMethodName = "/clutta_sync_grpc.PulseStreamService/SendPulse"
)

// PulseStreamServiceClient is the client API for PulseStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulseStreamServiceClient interface {
	SendPulse(ctx context.Context, opts ...grpc.CallOption) (PulseStreamService_SendPulseClient, error)
}

type pulseStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseStreamServiceClient(cc grpc.ClientConnInterface) PulseStreamServiceClient {
	return &pulseStreamServiceClient{cc}
}

func (c *pulseStreamServiceClient) SendPulse(ctx context.Context, opts ...grpc.CallOption) (PulseStreamService_SendPulseClient, error) {
	stream, err := c.cc.NewStream(ctx, &PulseStreamService_ServiceDesc.Streams[0], PulseStreamService_SendPulse_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pulseStreamServiceSendPulseClient{stream}
	return x, nil
}

type PulseStreamService_SendPulseClient interface {
	Send(*Pulse) error
	CloseAndRecv() (*StreamStatus, error)
	grpc.ClientStream
}

type pulseStreamServiceSendPulseClient struct {
	grpc.ClientStream
}

func (x *pulseStreamServiceSendPulseClient) Send(m *Pulse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pulseStreamServiceSendPulseClient) CloseAndRecv() (*StreamStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PulseStreamServiceServer is the server API for PulseStreamService service.
// All implementations must embed UnimplementedPulseStreamServiceServer
// for forward compatibility
type PulseStreamServiceServer interface {
	SendPulse(PulseStreamService_SendPulseServer) error
	mustEmbedUnimplementedPulseStreamServiceServer()
}

// UnimplementedPulseStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPulseStreamServiceServer struct {
}

func (UnimplementedPulseStreamServiceServer) SendPulse(PulseStreamService_SendPulseServer) error {
	return status.Errorf(codes.Unimplemented, "method SendPulse not implemented")
}
func (UnimplementedPulseStreamServiceServer) mustEmbedUnimplementedPulseStreamServiceServer() {}

// UnsafePulseStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseStreamServiceServer will
// result in compilation errors.
type UnsafePulseStreamServiceServer interface {
	mustEmbedUnimplementedPulseStreamServiceServer()
}

func RegisterPulseStreamServiceServer(s grpc.ServiceRegistrar, srv PulseStreamServiceServer) {
	s.RegisterService(&PulseStreamService_ServiceDesc, srv)
}

func _PulseStreamService_SendPulse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PulseStreamServiceServer).SendPulse(&pulseStreamServiceSendPulseServer{stream})
}

type PulseStreamService_SendPulseServer interface {
	SendAndClose(*StreamStatus) error
	Recv() (*Pulse, error)
	grpc.ServerStream
}

type pulseStreamServiceSendPulseServer struct {
	grpc.ServerStream
}

func (x *pulseStreamServiceSendPulseServer) SendAndClose(m *StreamStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pulseStreamServiceSendPulseServer) Recv() (*Pulse, error) {
	m := new(Pulse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PulseStreamService_ServiceDesc is the grpc.ServiceDesc for PulseStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clutta_sync_grpc.PulseStreamService",
	HandlerType: (*PulseStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPulse",
			Handler:       _PulseStreamService_SendPulse_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pulsestream.proto",
}
