name: Publish and release clutta-go library

on:
  workflow_dispatch: 
    inputs:
        versionType:
          description: 'Version type to increment'
          required: true
          type: choice
          options:
            - major
            - minor
            - patch
          default: minor

jobs:
  build-and-publish-go:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Fetch all tags
        run: git fetch --tags
      
      - name: Get latest go tag
        run: |
          current_tag=$(git tag -l 'clutta-go-v*' | sort -V | tail -n 1)
          if [ -z "$current_tag" ]; then
            current_tag="clutta-go-v0.0.0"
          fi
          echo "CURRENT_TAG=$current_tag" >> $GITHUB_ENV
      
      - name: Echo the current version
        run: echo "The current version is ${{ env.CURRENT_TAG }}"

      # - name: Increment version
      #   run: |
      #     current_tag=${CURRENT_TAG#learn-go-v}  # Strip "learn-go-v" from the tag
      #     IFS='.' read -r major minor patch <<< "$current_tag"

      #     case "${{ github.event.inputs.versionType}}" in
      #       major)
      #         major=$((major+1))
      #         minor=0
      #         patch=0
      #         ;;
      #       minor)
      #         minor=$((minor+1))
      #         patch=0
      #         ;;
      #       patch)
      #         patch=$((patch+1))
      #         ;;
      #     esac

      #     new_version="$major.$minor.$patch"
      #     echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      # - name: Echo the new version
      #   run: echo "The new version is ${{ env.NEW_VERSION }}"

      # - name: Create new tag
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git tag -a ${{ env.NEW_VERSION }} -m "Latest release ${{ env.NEW_VERSION }} for ${{ github.event.inputs.language }}"
      #     git push origin ${{ env.NEW_VERSION }}
      
      # - name: Create GitHub release
      #   if: success()
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.NEW_VERSION }}  
      #     release_name: Release ${{ env.NEW_VERSION }}
      #     body: |
      #       ## Changes
      #       - Release of ${{ env.NEW_VERSION }}
      #     draft: false
      #     prerelease: false
